repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
        exclude: '^brian2/_version.py$'
        files: '^brian2/.*\.pyi?$'
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        # We exclude all __init__.py files, since we use wildcard imports, etc.
        exclude: '^brian2/_version[.]py$|^brian2/tests/.*$|^brian2/.*__init__[.]py$'
        files: '^brian2/.*\.pyi?$'
        additional_dependencies: ['flake8-bugbear==23.5.9']
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: '^brian2/_version.py$'
        files: '^brian2/.*\.pyi?$'
  - repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
      - id: black
        exclude: '^brian2/_version.py$'
        files: '^brian2/.*\.pyi?$'
