# Environment of Brian dependencies, used in the RTD build
name: brian2_docs
channels:
- conda-forge
- defaults
dependencies:
- cython>=0.26
- ipython>=5.5.0
- jinja2>=2.9.6
- numpy>=1.13.1
- openblas>=0.2.19
- pip>=9.0.1
- py-cpuinfo>=3.3.0,!=4.0.0
- pyparsing>=2.2
- python=2.7
- scipy>=0.19.1
- setuptools>=36.3.0
- sphinx>=1.6.3
- sphinx_rtd_theme>=0.2.4
- sympy>=1.1.1
- weave>=0.15.0
- pip:
  - .

